# Generated by Django 5.0.14 on 2026-07-07 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DimCity',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'dim_city',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimCustomer',
            fields=[
                ('customer_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'dim_customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimDriver',
            fields=[
                ('driver_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('driver_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('license_number', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(default='Active', max_length=20)),
            ],
            options={
                'db_table': 'dim_driver',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimTime',
            fields=[
                ('time_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('day', models.IntegerField(blank=True, null=True)),
                ('quarter', models.IntegerField(blank=True, null=True)),
                ('month_name', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'dim_time',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimVehicle',
            fields=[
                ('vehicle_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('vehicle_type', models.CharField(blank=True, max_length=50, null=True)),
                ('license_plate', models.CharField(blank=True, max_length=20, null=True)),
                ('fuel_consumption', models.FloatField(default=10)),
                ('maintenance_cost', models.FloatField(default=0)),
                ('status', models.CharField(default='Active', max_length=20)),
            ],
            options={
                'db_table': 'dim_vehicle',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FactDelivery',
            fields=[
                ('delivery_id', models.AutoField(primary_key=True, serialize=False)),
                ('delivery_cost', models.IntegerField(blank=True, null=True)),
                ('delivery_time_hours', models.IntegerField(blank=True, null=True)),
                ('distance_km', models.FloatField(default=0)),
                ('delay_minutes', models.FloatField(default=0)),
                ('is_ontime', models.BooleanField(default=True)),
                ('status', models.CharField(default='Delivered', max_length=20)),
            ],
            options={
                'db_table': 'fact_delivery',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OpCity',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'op_city',
            },
        ),
        migrations.CreateModel(
            name='OpDriver',
            fields=[
                ('driver_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('driver_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('license_number', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(default='Active', max_length=20)),
            ],
            options={
                'db_table': 'op_driver',
            },
        ),
        migrations.CreateModel(
            name='OpVehicle',
            fields=[
                ('vehicle_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('vehicle_type', models.CharField(blank=True, max_length=50, null=True)),
                ('license_plate', models.CharField(blank=True, max_length=20, null=True)),
                ('fuel_consumption', models.FloatField(default=10)),
                ('maintenance_cost', models.FloatField(default=0)),
                ('status', models.CharField(default='Active', max_length=20)),
            ],
            options={
                'db_table': 'op_vehicle',
            },
        ),
        migrations.CreateModel(
            name='OpCustomer',
            fields=[
                ('customer_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.opcity')),
            ],
            options={
                'db_table': 'op_customer',
            },
        ),
        migrations.CreateModel(
            name='OpShipment',
            fields=[
                ('shipment_id', models.AutoField(primary_key=True, serialize=False)),
                ('shipment_date', models.DateTimeField(blank=True, null=True)),
                ('delivery_cost', models.IntegerField(blank=True, null=True)),
                ('delivery_time_hours', models.IntegerField(blank=True, null=True)),
                ('distance_km', models.FloatField(default=0)),
                ('delay_minutes', models.FloatField(default=0)),
                ('status', models.CharField(default='Delivered', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.opcity')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.opcustomer')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.opdriver')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.opvehicle')),
            ],
            options={
                'db_table': 'op_shipment',
            },
        ),
    ]
